### ISSUE TITLE
Improve Eureka support

### ISSUE THREAD

**Issue by bfg** [micronaut-projects/micronaut-core#1021]
Eureka client should be improved in order to allow better customization and to support containerized environments (for example AWS ECS).

I'm willing to contribute the code, i need to implement it anyway for my needs.

### Motivation

If micronaut service is started in docker container that container might contain bridged networking and hostname that is not reachable/resolvable by eureka server or clients that want to use them. For example, machine running docker container might have ip address `1.2.3.4` and docker container exposed port `9090`, but process in container has actual ip address `172.28.0.100` and listening port `8080`. In this case micronaut application should register in eureka as ip `1.2.3.4` and listening port `9090`, otherwise clients will try to contact unreachable address/port.

### Task List

- [x] improve default eureka application id, because current implementation doesn't work well if there are multiple instances of the same app are registered in eureka
- [x] add ability to register application in eureka under different name than `${micronaut.application.name}`
- [x] add ability to register with different hostname/ip-addr than `${micronaut.server.addr}`
- [x] add ability to register with different listening port than `${micronaut.server.port}`

**Comment by graemerocher** [comment]
Contributions welcome! Some of these may be resolvable through configuration / documentation. See the table https://docs.micronaut.io/latest/guide/configurationreference.html#io.micronaut.discovery.eureka.EurekaConfiguration$EurekaRegistrationConfiguration for the Eureka registration options

**Comment by bfg** [comment]
@graemerocher PR #1044 submitted (and tested on my micronaut app).
