### ISSUE TITLE
(AWS Lambda) Exception Handler invocation is non-deterministic  

### ISSUE THREAD

**Issue by alexwilbur** [micronaut-projects/micronaut-core#1706]
### Task List

- [X ] Steps to reproduce provided
- [X] Stacktrace (if present) provided
- [X] Example that reproduces the problem uploaded to Github
- [X] Full description of the issue provided (see below)

### Steps to Reproduce

1. Implement a class derived from RuntimeException and a corresponding exception handler for the specific subclass.
2. Also implement an exception handler for RuntimeException
3. Throw the derived class in an HTTP request handler
4. Deploy to AWS Lambda (using the Lambda proxy from Micronaut)
5. Invoke the HTTP request handler

### Expected Behaviour

The exception handler for the derived exception is always invoked.

### Actual Behaviour

Sometimes, apparently "at random" the RuntimeException handler is invoked.

### Environment Information

AWS Lambda (Java 8, standard AWS runtime)

### Example Application

https://github.com/alexwilbur/mn-issues

**Comment by alexwilbur** [comment]
I think this is related to https://github.com/micronaut-projects/micronaut-core/issues/1594
