### ISSUE TITLE
CLI app as daemon?

### ISSUE THREAD

**Issue by bmhm** [micronaut-projects/micronaut-core#2001]
### Task List

- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create a CLI app, with picolli
2. Create a scheduled bean (a bean with any @Scheduled annotation).
3. Run the app

### Expected Behaviour

The app should run as daemon.

### Actual Behaviour

The app does not find a http server and quits.

### Environment Information

- **Operating System**: Any, but Linux
- **Micronaut Version:** 1.2.0
- **JDK Version:** 11 (also tested 1.8), both openjdk-openj9.

### Example Application

I think it's easy enough to reproduce.

Well If I leave out Picolli and add http-server-netty as a dependency, it works as expected. But in this case, I'd like to see  CLI application which I can start using picolli CLI and the scheduler gets configured through picolli.

**Comment by bmhm** [comment]
Hi @graemerocher 

This was not a question. It was a missing feature.
