### ISSUE TITLE
Update jackson-databind over 2.9.9.3

### ISSUE THREAD

**Issue by Serverfrog** [micronaut-projects/micronaut-core#2093]
### Task List

- [ ] Update jackson-databind inside micronaut-runtime over 2.9.9.3
- [ ] scan the Project for known CVE's
- [ ] dont't find CVE-2019-14379 and CVE-2019-14439

### Expected Behaviour
No know Vurnabilitys should be found

### Actual Behaviour

CVE-2019-14379 and CVE-2019-14439 are found through io.micronaut:micronaut-runtime@1.2.1 › com.fasterxml.jackson.core:jackson-databind@2.9.9

### Environment Information

- **Micronaut Version:** 1.2.1

### Example Application
https://gitlab.com/Serverfrog/pipelinemerger/

**Comment by Serverfrog** [comment]
Need to reopen because the implementation is failing the build
(Only the Jackson-Databind needed an update, every other Jackson dependency is on 2.9.9)

**Comment by jameskleeh** [comment]
I saw the build fail - I'll push the change. No need to reopen
