### ISSUE TITLE
Bad contentType with HttpResponse<Flowable<*>> hangs server response

### ISSUE THREAD

**Issue by jisikoff** [micronaut-projects/micronaut-core#2724]
### Task List

- [X] Steps to reproduce provided
- [X] Stacktrace (if present) provided
- [X] Example that reproduces the problem uploaded to Github - https://github.com/jisikoff/micronaut-issue-2724
- [X] Full description of the issue provided (see below)

### Steps to Reproduce

1) Make a controller as follows:
```
@Controller("/test")
open class TestController() {
    
    @Get(value = "/hangs")
    open fun download():  HttpResponse<Flowable<String>> {
        val flowable = Flowable.just("one", "two", "three")
        return HttpResponse.ok(flowable).contentType("bad")
    }
}
```
2) curl the controller:
```
curl "http://localhost:8080/test/hangs"
```

### Expected Behaviour

The server should respond with something, preferable just with invalid content-type: bad

### Actual Behaviour

The server hangs indefinitely after throwing an exception internally here:
https://github.com/micronaut-projects/micronaut-core/blob/master/http/src/main/java/io/micronaut/http/MediaType.java#L428

### Stack 
Where the exception is thrown -I have no idea what code it's hanging on
```
<init>:428, MediaType (io.micronaut.http)
<init>:372, MediaType (io.micronaut.http)
lambda$registerDefaultConverters$13:199, DefaultRequestBinderRegistry (io.micronaut.http.bind)
convert:-1, 1494158416 (io.micronaut.http.bind.DefaultRequestBinderRegistry$$Lambda$386)
convert:139, DefaultConversionService (io.micronaut.core.convert)
convert:117, ConversionService (io.micronaut.core.convert)
getFirst:185, ConvertibleMultiValues (io.micronaut.core.convert.value)
contentType:493, HttpHeaders (io.micronaut.http)
getContentType:123, HttpMessage (io.micronaut.http)
getContentType:94, NettyMutableHttpResponse (io.micronaut.http.netty)
onComplete:1166, RoutingInBoundHandler$2 (io.micronaut.http.server.netty)
onComplete:1157, RoutingInBoundHandler$2 (io.micronaut.http.server.netty)
doOnComplete:73, ContextCompletionAwareSubscriber (io.micronaut.http.server.netty.async)
onComplete:71, CompletionAwareSubscriber (io.micronaut.core.async.subscriber)
onComplete:90, HalfSerializer (io.reactivex.internal.util)
onComplete:109, StrictSubscriber (io.reactivex.internal.subscribers)
drain:225, FlowableSwitchMap$SwitchMapSubscriber (io.reactivex.internal.operators.flowable)
onComplete:154, FlowableSwitchMap$SwitchMapSubscriber (io.reactivex.internal.operators.flowable)
onComplete:108, FlowableSubscribeOn$SubscribeOnSubscriber (io.reactivex.internal.operators.flowable)
run:-1, 561444403 (io.micronaut.http.context.ServerRequestTracingPublisher$1$$Lambda$636)
with:68, ServerRequestContext (io.micronaut.http.context)
onComplete:70, ServerRequestTracingPublisher$1 (io.micronaut.http.context)
onComplete:90, HalfSerializer (io.reactivex.internal.util)
onComplete:109, StrictSubscriber (io.reactivex.internal.subscribers)
onComplete:101, RxInstrumentedSubscriber (io.micronaut.reactive.rxjava2)
onComplete:73, FlowableSwitchIfEmpty$SwitchIfEmptySubscriber (io.reactivex.internal.operators.flowable)
onComplete:101, RxInstrumentedSubscriber (io.micronaut.reactive.rxjava2)
onComplete:120, BasicFuseableSubscriber (io.reactivex.internal.subscribers)
onComplete:101, RxInstrumentedSubscriber (io.micronaut.reactive.rxjava2)
complete:266, FlowableCreate$BaseEmitter (io.reactivex.internal.operators.flowable)
onComplete:258, FlowableCreate$BaseEmitter (io.reactivex.internal.operators.flowable)
lambda$buildResultEmitter$15:1493, RoutingInBoundHandler (io.micronaut.http.server.netty)
subscribe:-1, 659304395 (io.micronaut.http.server.netty.RoutingInBoundHandler$$Lambda$493)
subscribeActual:71, FlowableCreate (io.reactivex.internal.operators.flowable)
subscribe:14935, Flowable (io.reactivex)
subscribeActual:37, FlowableMap (io.reactivex.internal.operators.flowable)
subscribe:14935, Flowable (io.reactivex)
subscribeActual:32, FlowableSwitchIfEmpty (io.reactivex.internal.operators.flowable)
subscribe:14935, Flowable (io.reactivex)
subscribe:14885, Flowable (io.reactivex)
lambda$subscribe$0:52, ServerRequestTracingPublisher (io.micronaut.http.context)
run:-1, 1178364435 (io.micronaut.http.context.ServerRequestTracingPublisher$$Lambda$506)
with:68, ServerRequestContext (io.micronaut.http.context)
subscribe:52, ServerRequestTracingPublisher (io.micronaut.http.context)
subscribeActual:29, FlowableFromPublisher (io.reactivex.internal.operators.flowable)
subscribe:14935, Flowable (io.reactivex)
subscribe:14882, Flowable (io.reactivex)
run:82, FlowableSubscribeOn$SubscribeOnSubscriber (io.reactivex.internal.operators.flowable)
run:288, ExecutorScheduler$ExecutorWorker$BooleanRunnable (io.reactivex.internal.schedulers)
run:253, ExecutorScheduler$ExecutorWorker (io.reactivex.internal.schedulers)
safeExecute$$$capture:164, AbstractEventExecutor (io.netty.util.concurrent)
safeExecute:-1, AbstractEventExecutor (io.netty.util.concurrent)
 - Async stack trace
addTask:-1, SingleThreadEventExecutor (io.netty.util.concurrent)
execute:828, SingleThreadEventExecutor (io.netty.util.concurrent)
execute:818, SingleThreadEventExecutor (io.netty.util.concurrent)
schedule:171, ExecutorScheduler$ExecutorWorker (io.reactivex.internal.schedulers)
subscribeActual:48, FlowableSubscribeOn (io.reactivex.internal.operators.flowable)
subscribe:14935, Flowable (io.reactivex)
subscribeActual:49, FlowableSwitchMap (io.reactivex.internal.operators.flowable)
subscribe:14935, Flowable (io.reactivex)
subscribe:14885, Flowable (io.reactivex)
lambda$prepareRouteForExecution$9:1157, RoutingInBoundHandler (io.micronaut.http.server.netty)
execute:82, DefaultUriRouteMatch$1 (io.micronaut.web.router)
execute:122, RouteMatch (io.micronaut.web.router)
handleRouteMatch:723, RoutingInBoundHandler (io.micronaut.http.server.netty)
channelRead0:593, RoutingInBoundHandler (io.micronaut.http.server.netty)
channelRead0:160, RoutingInBoundHandler (io.micronaut.http.server.netty)
channelRead:99, SimpleChannelInboundHandler (io.netty.channel)
invokeChannelRead:377, AbstractChannelHandlerContext (io.netty.channel)
invokeChannelRead:363, AbstractChannelHandlerContext (io.netty.channel)
fireChannelRead:355, AbstractChannelHandlerContext (io.netty.channel)
channelRead:102, SimpleChannelInboundHandler (io.netty.channel)
invokeChannelRead:377, AbstractChannelHandlerContext (io.netty.channel)
invokeChannelRead:363, AbstractChannelHandlerContext (io.netty.channel)
fireChannelRead:355, AbstractChannelHandlerContext (io.netty.channel)
channelRead:102, MessageToMessageDecoder (io.netty.handler.codec)
invokeChannelRead:377, AbstractChannelHandlerContext (io.netty.channel)
invokeChannelRead:363, AbstractChannelHandlerContext (io.netty.channel)
fireChannelRead:355, AbstractChannelHandlerContext (io.netty.channel)
channelRead:433, HandlerPublisher (io.micronaut.http.netty.reactive)
invokeChannelRead:377, AbstractChannelHandlerContext (io.netty.channel)
invokeChannelRead:363, AbstractChannelHandlerContext (io.netty.channel)
fireChannelRead:355, AbstractChannelHandlerContext (io.netty.channel)
channelRead:219, HttpStreamsHandler (io.micronaut.http.netty.stream)
channelRead:121, HttpStreamsServerHandler (io.micronaut.http.netty.stream)
invokeChannelRead:377, AbstractChannelHandlerContext (io.netty.channel)
invokeChannelRead:363, AbstractChannelHandlerContext (io.netty.channel)
fireChannelRead:355, AbstractChannelHandlerContext (io.netty.channel)
channelRead:102, MessageToMessageDecoder (io.netty.handler.codec)
invokeChannelRead:377, AbstractChannelHandlerContext (io.netty.channel)
invokeChannelRead:363, AbstractChannelHandlerContext (io.netty.channel)
fireChannelRead:355, AbstractChannelHandlerContext (io.netty.channel)
channelRead:102, MessageToMessageDecoder (io.netty.handler.codec)
channelRead:111, MessageToMessageCodec (io.netty.handler.codec)
invokeChannelRead:377, AbstractChannelHandlerContext (io.netty.channel)
invokeChannelRead:363, AbstractChannelHandlerContext (io.netty.channel)
fireChannelRead:355, AbstractChannelHandlerContext (io.netty.channel)
channelRead:93, ChannelInboundHandlerAdapter (io.netty.channel)
channelRead:64, HttpServerKeepAliveHandler (io.netty.handler.codec.http)
invokeChannelRead:377, AbstractChannelHandlerContext (io.netty.channel)
invokeChannelRead:363, AbstractChannelHandlerContext (io.netty.channel)
fireChannelRead:355, AbstractChannelHandlerContext (io.netty.channel)
dequeue:191, FlowControlHandler (io.netty.handler.flow)
channelRead:153, FlowControlHandler (io.netty.handler.flow)
invokeChannelRead:377, AbstractChannelHandlerContext (io.netty.channel)
invokeChannelRead:363, AbstractChannelHandlerContext (io.netty.channel)
fireChannelRead:355, AbstractChannelHandlerContext (io.netty.channel)
fireChannelRead:436, CombinedChannelDuplexHandler$DelegatingChannelHandlerContext (io.netty.channel)
fireChannelRead:321, ByteToMessageDecoder (io.netty.handler.codec)
fireChannelRead:308, ByteToMessageDecoder (io.netty.handler.codec)
callDecode:422, ByteToMessageDecoder (io.netty.handler.codec)
channelRead:276, ByteToMessageDecoder (io.netty.handler.codec)
channelRead:251, CombinedChannelDuplexHandler (io.netty.channel)
invokeChannelRead:377, AbstractChannelHandlerContext (io.netty.channel)
invokeChannelRead:363, AbstractChannelHandlerContext (io.netty.channel)
fireChannelRead:355, AbstractChannelHandlerContext (io.netty.channel)
channelRead:286, IdleStateHandler (io.netty.handler.timeout)
invokeChannelRead:377, AbstractChannelHandlerContext (io.netty.channel)
invokeChannelRead:363, AbstractChannelHandlerContext (io.netty.channel)
fireChannelRead:355, AbstractChannelHandlerContext (io.netty.channel)
channelRead:1410, DefaultChannelPipeline$HeadContext (io.netty.channel)
invokeChannelRead:377, AbstractChannelHandlerContext (io.netty.channel)
invokeChannelRead:363, AbstractChannelHandlerContext (io.netty.channel)
fireChannelRead:919, DefaultChannelPipeline (io.netty.channel)
read:163, AbstractNioByteChannel$NioByteUnsafe (io.netty.channel.nio)
processSelectedKey:714, NioEventLoop (io.netty.channel.nio)
processSelectedKeysOptimized:650, NioEventLoop (io.netty.channel.nio)
processSelectedKeys:576, NioEventLoop (io.netty.channel.nio)
run:493, NioEventLoop (io.netty.channel.nio)
run:989, SingleThreadEventExecutor$4 (io.netty.util.concurrent)
run:74, ThreadExecutorMap$2 (io.netty.util.internal)
run:30, FastThreadLocalRunnable (io.netty.util.concurrent)
run:834, Thread (java.lang)
```

### Environment Information

- **Operating System**: MacOs Mohave
- **Micronaut Version:** 1.3.0.RC1
- **JDK Version:** OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.6+10, mixed mode)

### Example Application

- https://github.com/jisikoff/micronaut-issue-2724

**Comment by jisikoff** [comment]
@jameskleeh thanks for the prompt fix! My only concern with this is that the exception somehow caused the server response to hang forever and that other not yet found exceptions of this sort would also cause the same hanging behavior?

**Comment by jameskleeh** [comment]
> other not yet found exceptions of this sort would also cause the same hanging behavior

What course of action are you expecting or hoping we take based on that possibility?

**Comment by jisikoff** [comment]
Well I feel like this example (prior to your fix) demonstrates the possibility nicely and could be used to figure out why the server was hanging instead of bubbling the exception up.  I could try to help investigate that but I wouldn't really know where to start.  I'm mostly worried that ALL exceptions in this area of the code or pipeline would also cause a hang and that while fixing them individually is great it would be better to find why they are getting swallowed and hanging the server...

**Comment by jameskleeh** [comment]
@jisikoff If you would like to do some research on that area you are of course welcome to
