### ISSUE TITLE
Error occurred running Micronaut CLI: Could not find artifact io.micronaut:micronaut-bom:pom:1.3.4 in jcenter

### ISSUE THREAD

**Issue by breun** [micronaut-projects/micronaut-core#3020]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github (not applicable)
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Download https://github.com/micronaut-projects/micronaut-core/releases/download/v1.3.4/micronaut-1.3.4.zip
2. Extract micronaut-1.3.4.zip
3. Run `bin/mn`

### Expected Behaviour

Micronaut interactive shell starts.

### Actual Behaviour

Error message:

```| Error Error occurred running Micronaut CLI: Could not find artifact io.micronaut:micronaut-bom:pom:1.3.4 in jcenter (https://jcenter.bintray.com) (Use --stacktrace to see the full trace)```

The output with `--stacktrace` is the same.

### Environment Information

- **Operating System**: macOS 10.15.4
- **Micronaut Version:** 1.3.4
- **JDK Version:** 1.8.0_242

### Example Application

Not applicable.

**Comment by graemerocher** [comment]
Please try again.
