### ISSUE TITLE
Failed inject io.netty.channel.EventLoopGroup bean

### ISSUE THREAD

**Issue by degeorg** [micronaut-projects/micronaut-core#3050]
### Task List

- [ ] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [ ] Full description of the issue provided (see below)

### Steps to Reproduce

Create bean which provide io.netty.channel.EventLoopGroup and inject it. 

### Expected Behaviour

Bean must be injected

### Actual Behaviour

Error: io.micronaut.scheduling.instrument.ExecutorServiceInstrumenter$1 cannot be cast to io.netty.channel.EventLoopGroup

### Environment Information

- **Operating System**: Linux 5.5.15-200 x86_64
- **Micronaut Version:** 1.3.4
- **JDK Version:** 1.8.0_242-b06

### Example Application

- gist: https://gist.github.com/degeorg/96a0487fae662175acae61ad79ee7d41

### Stacktrace
``` 
io.micronaut.context.exceptions.BeanInstantiationException: Bean definition [loc.project.injection.Application] could not be loaded: Error instantiating bean of type [loc.project.injection.Application]: io.micronaut.scheduling.instrument.ExecutorServiceInstrumenter$1 cannot be cast to io.netty.channel.EventLoopGroup
	at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1359)
	at io.micronaut.context.DefaultApplicationContext.initializeContext(DefaultApplicationContext.java:236)
	at io.micronaut.context.DefaultBeanContext.readAllBeanDefinitionClasses(DefaultBeanContext.java:2547)
	at io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:204)
	at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:188)
	at io.micronaut.runtime.Micronaut.start(Micronaut.java:64)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:294)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:280)
	at loc.project.injection.Application.main(Application.java:23)
Caused by: io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type [loc.project.injection.Application]: io.micronaut.scheduling.instrument.ExecutorServiceInstrumenter$1 cannot be cast to io.netty.channel.EventLoopGroup
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1721)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingletonInternal(DefaultBeanContext.java:2407)
Caused by: io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type [loc.project.injection.Application]: io.micronaut.scheduling.instrument.ExecutorServiceInstrumenter$1 cannot be cast to io.netty.channel.EventLoopGroup

	at io.micronaut.context.DefaultBeanContext.loadContextScopeBean(DefaultBeanContext.java:1994)
	at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1357)
	... 8 common frames omitted
Caused by: java.lang.ClassCastException: io.micronaut.scheduling.instrument.ExecutorServiceInstrumenter$1 cannot be cast to io.netty.channel.EventLoopGroup
Caused by: java.lang.ClassCastException: io.micronaut.scheduling.instrument.ExecutorServiceInstrumenter$1 cannot be cast to io.netty.channel.EventLoopGroup

	at loc.project.injection.$ApplicationDefinition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1693)
	... 11 common frames omitted
```

**Comment by graemerocher** [comment]
Customizable event loops are implemented in Micronaut 2.x
