### ISSUE TITLE
micronaut-redis-lettuce can't be compiled by GraalVM

### ISSUE THREAD

**Issue by qiuzhanghua** [micronaut-projects/micronaut-core#3073]
### Task List

- [ ] Get source code
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [ ] Full description of the issue provided (see below)

### Get source code

```bash
git clone https://github.com/qiuzhanghua/perf.git
gradle assemble
native-image --no-server -cp build/libs/perf-0.1-all.jar --initialize-at-run-time=io.micronaut.configuration.lettuce.session.$RedisHttpSessionConfigurationDefinition --initialize-at-build-time=reactor.core.publisher.Mono --initialize-at-build-time=reactor.core.publisher.Flux --initialize-at-build-time=reactor.core.publisher.Flux$$Lambda$105/0x00000007c1338c40
```

### Expected Behaviour
produce native code

### Actual Behaviour

```text
[perf:5645]    classlist:   4,966.92 ms,  1.20 GB
[perf:5645]        (cap):   2,298.72 ms,  1.20 GB
[perf:5645]        setup:   3,483.65 ms,  1.20 GB
[perf:5645]     analysis:  35,611.93 ms,  5.38 GB
Error: Classes that should be initialized at run time got initialized during image building:
 reactor.core.publisher.Flux$$Lambda$104/0x00000007c1322040 was unintentionally initialized at build time. To see why reactor.core.publisher.Flux$$Lambda$104/0x00000007c1322040 got initialized use -H:+TraceClassInitialization

Error: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
Error: Image build request failed with exit status 1
```

### Environment Information

-  **Mac OS Catlina:** 10.15.4
- **Micronaut Version:** 1.3.4
- **JDK Version:** openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment GraalVM CE 20.0.0 (build 11.0.6+9-jvmci-20.0-b02)
OpenJDK 64-Bit Server VM GraalVM CE 20.0.0 (build 11.0.6+9-jvmci-20.0-b02, mixed mode, sharing)

### Example Application

-  https://github.com/qiuzhanghua/perf.git

**Comment by ilopmar** [comment]
Related GraalVM issue: https://github.com/oracle/graal/issues/1036
