### ISSUE TITLE
Invocation instrumenter does not work with ThreadFactory

### ISSUE THREAD

**Issue by okosatka** [micronaut-projects/micronaut-core#4066]
### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github: https://github.com/okosatka/micronaut-bug-instrumenter
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Inject ThreadFactory in your service/controller.
```java
    @Inject @Named(TaskExecutors.IO) ExecutorService executorService;
    @Inject ThreadFactory threadFactory;

    @Get(uri = "/thread-factory", produces = MediaType.TEXT_PLAIN)
    public String threadFactory() throws InterruptedException {
        ThreadContext.put(CORRELATION_ID, VALUE);
        var latch = new CountDownLatch(1);
        var runnable = new MyRunnable(latch);
        var t = threadFactory.newThread(runnable);
        t.start();
        if (latch.await(1, TimeUnit.SECONDS)) {
            return VALUE;
        }
        return "WRONG";
    }

    static class MyRunnable implements Runnable {
        private final CountDownLatch latch;

        public MyRunnable(CountDownLatch latch) {
            this.latch = latch;
        }

        @Override
        public void run() {
            if (VALUE.equals(ThreadContext.get(CORRELATION_ID))) {
                latch.countDown();
            }
        }
    }
```
2. Provide an `InvocationInstrumenter`.
```java
    @Override
    public InvocationInstrumenter newInvocationInstrumenter() {
        Map<String, String> context = ThreadContext.getContext();
        return () -> {
            ThreadContext.putAll(context);
            return cleanup -> ThreadContext.clearMap();
        };
    }
```
3. Run a thread on the `ThreadFactory`.

There tests on a linked example: https://github.com/okosatka/micronaut-bug-instrumenter that prove that instrumenting on `ExectorService` works and intrumenting `ThreadFactory` threads doesn't.
It worked on 1.3.3 with similar code (API change).

### Expected Behaviour

`ThreadFactory` threads should be instrumented by provided instrumenter.

### Actual Behaviour

A `Runnable` executed on `ThreadFactory` wasn't instrumented.

### Environment Information

- **Operating System:** macOS 10.15.6 
- **Micronaut Version:** 2.0.1
- **JDK Version:** 11

### Example Application

https://github.com/okosatka/micronaut-bug-instrumenter

**Comment by dstepanov** [comment]
Instrumenting `ThreadFactory` was a mistake in 1.3 because there are cases like pooling where threads are long-running and it makes the instrumentation to leak the context.

I recommend you use `@Named(TaskExecutors.IO) ExecutorService executorService` or you can add the instrumentation yourself just like it's done for `ExecutorService` in `ExecutorServiceInstrumenter`.

**Comment by graemerocher** [comment]
@dstepanov we probably need upgrade docs to explain this. See https://github.com/micronaut-projects/micronaut-core/blob/2.0.x/src/main/docs/guide/introduction/upgrading.adoc

**Comment by dstepanov** [comment]
@graemerocher Added https://github.com/micronaut-projects/micronaut-core/pull/4069
