### ISSUE TITLE
Get cookies when opening WebSocket connection

### ISSUE THREAD

**Issue by adrienpessu** [micronaut-projects/micronaut-core#4097]
### Task List

- [ ] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

Using WebSocket with Micronaut `@ServerWebSocket`, when opening the connection, it could be nice to be able to get the cookie from the request.
The goal is to be able to authenticate users with HttpOnly cookies.

### Expected Behaviour

```
@OnOpen
    Publisher<String> onOpen(String username, WebSocketSession session) {
        try {
        
            // feature request - start
        
            Map cookies = session.session.request.cookies
            
            // or
            Map cookiesAlternative = session.requestCookies
            
            // feature request - end
            
            return broadcaster.broadcast(mapper.writeValueAsString(event), onlyMe(username));
        } catch (Exception exception) {
            throw exception
        }
    }
```

### Actual Behaviour

The request is not reachable with the `session` parameter. However, in debug, we can see that the request is a private attribute of the `session`

### Environment Information

- **Operating System**: All
- **Micronaut Version:** 2.x
- **JDK Version:** 8

### Example Application

https://gist.github.com/adrienpessu/7e2e0ec7578b9bdcf6bd28848b1dd0b5

**Comment by adrienpessu** [comment]
By digging into the code I have found : https://github.com/micronaut-projects/micronaut-core/blob/2.0.x/validation/src/main/java/io/micronaut/validation/websocket/WebSocketVisitor.java
