### ISSUE TITLE
Micronaut generates the wrong openapi yaml when using `Schema(required=true)` annotation

### ISSUE THREAD

**Issue by naddeoa** [micronaut-projects/micronaut-core#4579]
Thanks for reporting an issue, please review the task list below before submitting the
issue. Your issue report will be closed if the issue is incomplete and the below tasks not completed.

NOTE: If you are unsure about something and the issue is more of a question a better place to ask questions is on Stack Overflow (https://stackoverflow.com/tags/micronaut) or Gitter (https://gitter.im/micronautfw/). DO NOT use the issue tracker to ask questions.

### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [x ] Example that reproduces the problem uploaded to Github (https://github.com/naddeoa/micronaut-swagger-yml-bug)
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Check out https://github.com/naddeoa/micronaut-swagger-yml-bug
2. `gw build`
3. `cat build/tmp/kapt3/classes/main/META-INF/swagger/repro-0.1.yml`

### Expected Behaviour

The `required` field in the yaml should have a value of `true`

### Actual Behaviour

`required` is actually a list with an entry of `"true"`. The repo also has an example of the yaml file in the README that you can see without having to build yourself just to glance. This also results in the generated classes being nullable when they shouldn't be for every language.

### Environment Information

- **Operating System**: OSX 10.15.7 (19H2)
- **Micronaut Version:** https://github.com/naddeoa/micronaut-swagger-yml-bug/blob/master/build.gradle.kts#L36
- **JDK Version:** 1.8 (https://github.com/naddeoa/micronaut-swagger-yml-bug/blob/master/build.gradle.kts#L87)

### Example Application

- https://github.com/naddeoa/micronaut-swagger-yml-bug
