### ISSUE TITLE
CDI Alignment Tasks

### ISSUE THREAD

**Issue by graemerocher** [micronaut-projects/micronaut-core#4658]
The following issue covers the tasks required to assign Micronaut's DI system with CDI such that future compatibility with CDI lite can be achieved. This is an epic issue covering many other sub issues that need to implement to correctly support a proposed future CDI lite specification.

### Task List

- [x] Support for Annotations on Generic Type Arguments. (Fixed in https://github.com/micronaut-projects/micronaut-core/pull/4703)
- [x] Support for `@NonBinding` and using members in qualifiers. (See https://github.com/micronaut-projects/micronaut-core/issues/4769)
- [x] Support for Narrowing Injection by Type Arguments and Qualifiers on Type Arguments (PR #5082)
- [x] Support for Constructor Interceptors (PR https://github.com/micronaut-projects/micronaut-core/pull/5239)
- [x] Support for `@Named` without a value https://jakarta.ee/specifications/cdi/3.0/jakarta-cdi-spec-3.0.html#named_at_injection_point (PR #5386)
- [x] Support for `@Any` qualifier (Issue #5155, PR #5156)
- [x] Support for `@Dependent` and `@TransientReference` https://jakarta.ee/specifications/cdi/3.0/jakarta-cdi-spec-3.0.html#dependent_destruction (PR #5612)
- [x] Allow controlling annotation inheritance with `java.lang.annotation.Inherited` and possibly a member of `@Bean` (PR #5643)
- [x] Support for `@Factory` to define [bean fields](https://jakarta.ee/specifications/cdi/3.0/jakarta-cdi-spec-3.0.html#producer_field) (See https://github.com/micronaut-projects/micronaut-core/issues/4797, PR https://github.com/micronaut-projects/micronaut-core/pull/5343)
- [x] [Altering the exposed type](https://jakarta.ee/specifications/cdi/3.0/jakarta-cdi-spec-3.0.html#restricting_bean_types) via `@Typed` (Issue #5098, PR https://github.com/micronaut-projects/micronaut-core/pull/5106)
- [x] Allow `@Ordered` (later mapped at compilation to `@Priority`) to be used as fallback in order to support [bean priority and alternatives](https://jakarta.ee/specifications/cdi/3.0/jakarta-cdi-spec-3.0.html#declaring_selected_alternatives) (PR #5433)
- [x] CDI-style [interceptor binding](https://jakarta.ee/specifications/cdi/3.0/jakarta-cdi-spec-3.0.html#interceptors) (Fixed in https://github.com/micronaut-projects/micronaut-core/pull/4988)
- [ ] [Repeatable qualifiers](https://docs.jboss.org/cdi/spec/2.0/cdi-spec.html#repeating_qualifiers) - PR #6201
- [ ] [@TransientReference](https://docs.jboss.org/cdi/spec/2.0/cdi-spec.html#dependent_destruction)
- [ ] Interceptor binding with annotation member values

Some functionality differs but can be supported just through annotation mappers that handle the CDI annotations and external integrations not part of Micronaut core:

- [ ] Support for `@Specializes` to control [inheriting qualifiers and scopes](https://jakarta.ee/specifications/cdi/3.0/jakarta-cdi-spec-3.0.html#specialization) 
- [ ] A `@Default` qualifier (same as no qualifier, could be an internal meta annotations) to inject the [default bean](https://jakarta.ee/specifications/cdi/3.0/jakarta-cdi-spec-3.0.html#injection_point_default_qualifier)
- [ ] CDI-style [event observers](https://jakarta.ee/specifications/cdi/3.0/jakarta-cdi-spec-3.0.html#observer_methods)
- [ ] API compatibility for subset of CDI in `micronaut-inject-cdi` subproject
- [ ] Support for CDI lite build time extensions (see https://github.com/Ladicek/quarkus-fork/pull/7)
* [Observer Methods](https://jakarta.ee/specifications/cdi/3.0/jakarta-cdi-spec-3.0.html#observer_methods) - map to `@EventListener` and fail compilation if more than one argument
* [Disposer Methods](https://jakarta.ee/specifications/cdi/3.0/jakarta-cdi-spec-3.0.html#disposer_method) - simple map to `@PreDestroy` and fail compilation if more than one argument
* [Producer Methods](https://jakarta.ee/specifications/cdi/3.0/jakarta-cdi-spec-3.0.html#producer_method)) - map to `@Factory` with `@Bean` methods
* `@ApplicationScoped` -> `@Context` & `@Singleton`
* `@ObservesAsync` -> `@EventListener` & `@Async`
* `@Dependent` -> `@Prototype`
* `@Destroyed(ApplicationScoped.class)` -> `@EventListener ShutdownEvent`
* `@Initialized(ApplicationScoped.class)` -> `@EventListener StartupEvent`

**Comment by gerdogdu** [comment]
I am interested on this :)

**Comment by graemerocher** [comment]
@gerdogdu happy to collaborate and would be interested in your feedback as we progress
