### ISSUE TITLE
Configure/change behavior of AbstractResource in regards to embedded resource for a single resource

### ISSUE THREAD

**Issue by hbxu** [micronaut-projects/micronaut-core#5009]
No control in behavior of AbstractResource for embedded resources.
Actual:
- Single resource within embedded AbstractResource will result into an Object
- Multiple resources within embedded AbstractResource will result into an Array of Objects

Expect:
- Single resource within embedded AbstractResource will result into an Array with one Object

### Task List

- [X] Steps to reproduce provided
- [X] Stacktrace (if present) provided, not applicable
- [X] Example that reproduces the problem uploaded to Github
- [X] Full description of the issue provided (see below)

### Steps to Reproduce

1. Using AbstractResource: https://github.com/hbxu/testcase-one-item-list/blob/master/src/main/java/com/example/testcase/Article.java
2. Using POJO with Jackson annotations: https://github.com/hbxu/testcase-one-item-list/blob/master/src/main/java/com/example/testcase/ArticleNew.java

### Expected Behaviour

_embedded with single item, should be in an array:
```
{
  ...
  "_embedded": [{
     "foo": "bar"
  }]
  ...
}
```

### Actual Behaviour

_embedded with single item, not in an array:
```
{
  ...
  "_embedded": {
     "foo": "bar"
  }
  ...
}
```

see the test cases in example application

### Environment Information

- **Operating System**: Windows 10
- **Micronaut Version:** 2.3.2
- **JDK Version:** OpenJDK 15

### Example Application

- https://github.com/hbxu/testcase-one-item-list

**Comment by jameskleeh** [comment]
This is a breaking change that would have to wait until Micronaut 3
