### ISSUE TITLE
jakarta.inject.Singleton not loading, where javax.inject.Singleton works correctly.

### ISSUE THREAD

**Issue by msgilligan** [micronaut-projects/micronaut-core#5103]
Micronaut fails to load a class annotated with `jakarta.inject.Singleton`, but simply changing back to `javax.inject.Singleton` makes it work.

The example class is [EchoJsonRpcService.java](https://github.com/ConsensusJ/consensusj/blob/msgilligan-show-micronaut-jakarta-inject-issue/consensusj-jsonrpc-daemon/src/main/java/org/consensusj/jsonrpc/daemon/EchoJsonRpcService.java)

Commit https://github.com/ConsensusJ/consensusj/commit/707248e3f343817fcc16253f7a6c0c362306ef82 is the difference between success and failure.

I suspect the problem may be related to the superclasses (1 abstract class and 2 interfaces).

### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided

### Steps to Reproduce

1. `JAVA_HOME` to JDK 11
2. Git clone [ConsensusJ/consensusj](https://github.com/ConsensusJ/consensusj)
3. `git checkout msgilligan-show-micronaut-jakarta-inject-issue`
4. `./gradlew consensusj-jsonrpc-daemon:test`
 
### Expected Behaviour

The `Singleton` should load, and the test ['hit it with a JSON-RPC request'()](https://github.com/ConsensusJ/consensusj/blob/msgilligan-show-micronaut-jakarta-inject-issue/consensusj-jsonrpc-daemon/src/test/groovy/org/consensusj/jsonrpc/daemon/ApplicationSpec.groovy#L28-L39) should pass.

### Actual Behaviour

Exception during test.

```
2021-03-10T23:15:51.3391060Z ApplicationSpec > hit it with a JSON-RPC request STANDARD_ERROR
2021-03-10T23:15:51.3392624Z     Mar 10, 2021 11:15:51 PM io.micronaut.http.server.netty.RoutingInBoundHandler logException
2021-03-10T23:15:51.3394629Z     SEVERE: Unexpected error occurred: Failed to inject value for parameter [jsonRpcService] of class: org.consensusj.jsonrpc.daemon.JsonRpcController
2021-03-10T23:15:51.3395754Z 
2021-03-10T23:15:51.3398387Z     Message: No bean of type [org.consensusj.jsonrpc.JsonRpcService] exists. Make sure the bean is not disabled by bean requirements (enable trace logging for 'io.micronaut.context.condition' to check) and if the bean is enabled then ensure the class is declared a bean and annotation processing is enabled (for Java and Kotlin the 'micronaut-inject-java' dependency should be configured as an annotation processor).
2021-03-10T23:15:51.3401159Z     Path Taken: new JsonRpcController([JsonRpcService jsonRpcService])
2021-03-10T23:15:51.3403689Z     io.micronaut.context.exceptions.DependencyInjectionException: Failed to inject value for parameter [jsonRpcService] of class: org.consensusj.jsonrpc.daemon.JsonRpcController
2021-03-10T23:15:51.3406017Z 
2021-03-10T23:15:51.3409049Z     Message: No bean of type [org.consensusj.jsonrpc.JsonRpcService] exists. Make sure the bean is not disabled by bean requirements (enable trace logging for 'io.micronaut.context.condition' to check) and if the bean is enabled then ensure the class is declared a bean and annotation processing is enabled (for Java and Kotlin the 'micronaut-inject-java' dependency should be configured as an annotation processor).
2021-03-10T23:15:51.3411504Z     Path Taken: new JsonRpcController([JsonRpcService jsonRpcService])
2021-03-10T23:15:51.3413628Z     	at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:1034)
2021-03-10T23:15:51.3416217Z     	at org.consensusj.jsonrpc.daemon.$JsonRpcControllerDefinition.build(Unknown Source)
2021-03-10T23:15:51.3418156Z     	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1943)
2021-03-10T23:15:51.3420906Z     	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingletonInternal(DefaultBeanContext.java:2724)
2021-03-10T23:15:51.3423851Z     	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:2710)
2021-03-10T23:15:51.3426723Z     	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:2382)
2021-03-10T23:15:51.3429352Z     	at io.micronaut.context.DefaultBeanContext.access$100(DefaultBeanContext.java:77)
2021-03-10T23:15:51.3431544Z     	at io.micronaut.context.DefaultBeanContext$4.getTarget(DefaultBeanContext.java:439)
2021-03-10T23:15:51.3433049Z     	at io.micronaut.context.DefaultBeanContext$4.invoke(DefaultBeanContext.java:482)
2021-03-10T23:15:51.3434728Z     	at io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:312)
2021-03-10T23:15:51.3460672Z     	at io.micronaut.web.router.RouteMatch.execute(RouteMatch.java:118)
```

Full Github Actions job is here: https://github.com/ConsensusJ/consensusj/runs/2081757129
Gradle build scan is here: https://scans.gradle.com/s/4doezawpjeiwq/tests

### Environment Information

- **Operating System**: Linux, macOS, and Windows
- **Micronaut Version:** 2.4.0
- **JDK Version:** 11

### Example Application

Provided above.

**Comment by jameskleeh** [comment]
This is an issue only with incremental compilation. With that turned off it works as expected

**Comment by msgilligan** [comment]
I switched back to `jakarta.inject` in the two places this issue was showing up, disabled incremental compilation https://github.com/ConsensusJ/consensusj/commit/4aa5c89a2064ea42893ed7e69d232b93c5d19070 and everything is working.

Thanks @jameskleeh !
