### ISSUE TITLE
Micronaut crashes with java.lang.OutOfMemoryError when parsing properties

### ISSUE THREAD

**Issue by thestarmaker** [micronaut-projects/micronaut-core#5172]
### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)
- [x] Debugged reason of what goes wrong :wink: 

### Steps to Reproduce

1. Create simple WebApplication, deploy to Kubernetes where k8s-env property source is available (or potentially any other property source, I have not tried)
2. Make sure there are many properties in the property source and their names are long-winded i.e. have many underscores (like `MR_ROCHER_IGNORED_BIG_O_AND_CHANCE_THAT_OUR_DEVS_ARE_ALSO_COWBOYS_WHICH_MAKES_ME_DEBUG_THIS=this-can-really-be-anything-does-not-matter`)
3. Deploy the app (start the app), watch it get java.lang.OutOfMemoryError

### Expected Behaviour
App does not crash

### Actual Behaviour
App crashes with java.lang.OutOfMemoryError

### Environment Information

- **Operating System**: Red Hat Linux
- **Micronaut Version:** 2.4.1
- **JDK Version:** openjdk11:11.0.9_11_LTS

### Post Mortem
So what actually happens is that `io.micronaut.context.env.PropertySourcePropertyResolver` (whaaat? I thought Spring names were terrible :stuck_out_tongue_closed_eyes: ) tries to parse all properties coming from the environment and as it goes attempts to perform "Property Value Normalization". This means that given a simple property `I_LIKE_SHROOMS=chanterelle` the routine will generate multiple permutations:
* i.like.shrooms=chanterelle
* i.like-shrooms=chanterelle
* i-like-shrooms=chanterelle

and will store all those in `io.micronaut.context.env.PropertySourcePropertyResolver.catalog` `Map<String, Object>[]`. 
We are deploying to OpenShift Kubernetes flavour and for some reason (those people!) our environment contains 3210 properties with up to 17 underscores each. This creates 131072 permutations. Given that all 3210 properties are around ~216KBytes in size if we were to repeat it 131072 times it would give us ~28GB worth of `catalog` resulting in OutOfMemoryError.

Can somebody please check if there is a better way of doing whatever `PropertySourcePropertyResolver` tries to do?

**Comment by graemerocher** [comment]
There are various ways you can control this. 

1. You can disable properties from the environment all together https://docs.micronaut.io/latest/api/io/micronaut/context/ApplicationContextBuilder.html#environmentPropertySource-boolean-
2. You can narrow the properties to include to only those you want https://docs.micronaut.io/latest/api/io/micronaut/context/ApplicationContextBuilder.html#environmentVariableIncludes-java.lang.String...-
3. You can exclude offending properties https://docs.micronaut.io/latest/api/io/micronaut/context/ApplicationContextBuilder.html#environmentVariableExcludes-java.lang.String...-

This can be done in your main method:

```java
Micronaut.build(args)
    .environmentPropertySource(false)
    .start();
```

**Comment by goeh** [comment]
Interesting... I didn't realize this happened behind the scenes. I looked at the code I could not find any debug/trace logging that tells me how many properties was actually loaded at the end. I noticed trace logging for each property but maybe a summary at the end would be useful to help debugging these problems.
