### ISSUE TITLE
Non-daemon threads are getting killed before completion on shutdown.

### ISSUE THREAD

**Issue by svmsharma20** [micronaut-projects/micronaut-core#5375]
We have an application in that we have some non-daemon threads which run in the background. Whenever a shutdown is triggered we set a flag that tells non-daemon threads to wrap up their work and then stop. It takes some amount of time for them to wrap the task they are currently processing. We are using @PreDestroy to set a flag which is used to tell all the non-daemon threads to wrap their task. From the java application perspective, JVM should wait for a non-daemon thread to get complete but, it is not happening, as soon as the @PreDestroy method gets complete, the Micronaut application gets shut down killing the non-daemon threads.

### Task List

- [ ] Steps to reproduce provided
- [ ] Example that reproduces the problem uploaded to Github
- [ ] Console output provided

### Steps to Reproduce

1. Start the application using ./gradlew run
2. When the application is up and running from a different terminal get the PID of the application using the below cmd:
	```ps ax | grep java | grep Application```
3. After getting the PID run the below cmd to triggered the shutdown within 1 minute of application start:
	```kill -INT <pid>```

### Expected Behaviour
On completion, The "Thread processing completed" should be present.

##### Tell us what should happen
Micronaut should wait for the non-daemon thread to get complete. On completion, the non-daemon thread will print "Thread processing completed" and then Micronaut should get shut down.

### Actual Behaviour
The "Thread processing completed" message is missing from the console.

##### Tell us what happens instead
Micronaut exits immediately after the @PreDestroy method gets completed and is not waiting for the non-daemon thread to complete. Since the processing of the non-daemon thread didn't complete "Thread processing completed" message is missing from the console.

### Environment Information

- **Operating System**: Linux
- **Micronaut Version:** 2.4.1
- **JDK Version:** 11

### Example Application

- https://github.com/svmsharma20/MicronautShutdownIssue

### Console output
```
$ ./gradlew run
Starting a Gradle Daemon, 2 stopped Daemons could not be reused, use --status for details

> Task :compileJava
Note: Creating bean classes for 1 type elements

> Task :run
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
 __  __ _                                  _   
|  \/  (_) ___ _ __ ___  _ __   __ _ _   _| |_ 
| |\/| | |/ __| '__/ _ \| '_ \ / _` | | | | __|
| |  | | | (__| | | (_) | | | | (_| | |_| | |_ 
|_|  |_|_|\___|_|  \___/|_| |_|\__,_|\__,_|\__|
  Micronaut (v2.4.1)

***************** On Startup *****************
***************** On Shutdown *****************

> Task :run FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':run'.
> Process 'command '/usr/lib/jvm/java-11-openjdk-amd64/bin/java'' finished with non-zero exit value 130

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 44s
2 actionable tasks: 2 executed
```

**Comment by svmsharma20** [comment]
Hi Team,

Can someone confirm the above bug and provide some update on this? Depending upon the response we might need to make changes in our architecture.
CC: @jameskleeh.

Thank you,
Shivam

**Comment by graemerocher** [comment]
Frankly I think this is working as designed. See here for an explanation https://www.baeldung.com/java-daemon-thread#difference-between-daemon-and-user-threads

The JVM doesn't wait until daemon threads complete before exiting and this is by design. If you don't want this behaviour then you should create a user thread instead of a daemon thread.

**Comment by graemerocher** [comment]
Actually sorry, I see you mentioned the opposite. Can be implemented with:

```java
package com.example;

import io.micronaut.context.annotation.Context;

import javax.annotation.PostConstruct;
import javax.annotation.PreDestroy;
import javax.inject.Singleton;

@Context
@Singleton
public class AppLifeCycle {

    private Thread thread1;

    @PostConstruct
    void onStartup(){
        System.out.println("***************** On Startup *****************");
        this.thread1 = new Thread( () -> {
            try {
                Thread.sleep(60000);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
            System.out.println("Thread processing completed");
        });
        thread1.setDaemon(false);
        thread1.start();
    }

    @PreDestroy
    void onShutdown(){
        try {
            thread1.join();
        } catch (InterruptedException e) {
        }
        System.out.println("***************** On Shutdown *****************" );
    }

}
```

**Comment by sandeep14-singh** [comment]
> Actually sorry, I see you mentioned the opposite. Can be implemented with:
> 
> ```java
> package com.example;
> 
> import io.micronaut.context.annotation.Context;
> 
> import javax.annotation.PostConstruct;
> import javax.annotation.PreDestroy;
> import javax.inject.Singleton;
> 
> @Context
> @Singleton
> public class AppLifeCycle {
> 
>     private Thread thread1;
> 
>     @PostConstruct
>     void onStartup(){
>         System.out.println("***************** On Startup *****************");
>         this.thread1 = new Thread( () -> {
>             try {
>                 Thread.sleep(60000);
>             } catch (InterruptedException e) {
>                 e.printStackTrace();
>             }
>             System.out.println("Thread processing completed");
>         });
>         thread1.setDaemon(false);
>         thread1.start();
>     }
> 
>     @PreDestroy
>     void onShutdown(){
>         try {
>             thread1.join();
>         } catch (InterruptedException e) {
>         }
>         System.out.println("***************** On Shutdown *****************" );
>     }
> 
> }
> ```

While this solution would surely work, we are just trying to understand what are we missing in our original code/assumption. Ideally shutdown should happen after all user threads have finished their tasks & we should not be required to call ```join```.
Our actual service code has many user threads and hence we dont want to call ```join``` on each one of them.

**Comment by graemerocher** [comment]
Well Micronaut is not doing anything special here with regards to killing user threads. The only thing it does is register a shutdown hook that ensures pre destroys are invoked:

https://github.com/micronaut-projects/micronaut-core/blob/50406d0c9175f484c0a7e6368c1963f35df1728a/context/src/main/java/io/micronaut/runtime/Micronaut.java#L112-L123

The rest is just the regular behaviour of the JVM.
