### ISSUE TITLE
Path variable in @Client path causes path to be ignored on client calls

### ISSUE THREAD

**Issue by austinb7h** [micronaut-projects/micronaut-core#5670]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] ~Example that reproduces the problem uploaded to Github~ Snippet provided
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Try to create a declarative client with a path-variable (see snippet below)
2. Perform HTTP call with client
3. Context path from client is missing in request path

### Expected Behaviour

Context path should be included in the HTTP request made by the client

### Actual Behaviour

Only the path on the declarative client method, is used in the request.

### Environment Information

- **Operating System**: macOS 14.1.1
- **Micronaut Version:** 2.5.7
- **JDK Version:** 11

### Example Application

```
@Client(value = "somehost", path = "/pets/{storeUid}") 
public interface PetClient {

  @Post("/dosomething")
  void doSomething(...);
}
```
For the above example snippet, the parameterised context path is not included in the request path when calling `doSomething`.

This is because when `DefaultHttpClient.prependContextPath` is called, we haven't substituted in the `storeUid` value, and so we catch and swallow a `URISyntaxException` when trying to make a URI with a context path of `/pets/{storeUid}`.

Because we catch-swallow the exception, we ignore the context path, and just take the `/dosomething` path, creating a rather hard to diagnose error.

Either path-variables should be explicitly validated against in the context-path, or the substitution performed earlier.

**Comment by jameskleeh** [comment]
So after looking at the code and considering the idea of a context path, I don't think we can support uri variables in the context path. I'll work on ensuring the exception is not swallowed and the error is obvious.
