### ISSUE TITLE
After Micronaut 3.0.0-M3 release checklist

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-core#5757]
- [ ] Merge [Use Micronaut 3.0.0-M3](https://github.com/micronaut-projects/micronaut-rxjava2/pull/7) in RxJava 2.
- [ ] Release version 1.0.0-M2 of Micronaut Rx Java 2.
- [ ] Merge [Use Micronaut 3.0.0-M3](https://github.com/micronaut-projects/micronaut-rxjava3/pull/117) in RxJava 3.
- [ ] Release version 2.0.0-M1 of Micronaut Rx Java 3.
- [ ] Merge [Use Micronaut 3.0.0-M3](https://github.com/micronaut-projects/micronaut-reactor/pull/109) in Reactor.
- [ ] Release version 2.0.0-M1 of Micronaut Reactor.
- [ ] Merge [Use Micronaut 3.0.0-M3](https://github.com/micronaut-projects/micronaut-discovery-client/pull/280) in Discovery Client.
- [ ] Release version 3.0.0-M1 of Micronaut Discovery Client.
- [ ] Release version 3.0.0-M2 of Micronaut Security
- [ ] Release version 3.0.0-M1 of Micronaut Views
- [ ] Release version 4.0.0-RC2 of Micronaut Kafka
- [ ] Release version 2.0.0-RC1 of Micronaut Oracle Cloud after merging https://github.com/micronaut-projects/micronaut-oracle-cloud/pull/226

**Comment by graemerocher** [comment]
As discussed in https://github.com/micronaut-projects/micronaut-liquibase/pull/173 liquibase doesn't need anything from Micronaut 3.0 and could have been released with 2.5.x

**Comment by ilopmar** [comment]
> As discussed in [micronaut-projects/micronaut-liquibase#173](https://github.com/micronaut-projects/micronaut-liquibase/pull/173) liquibase doesn't need anything from Micronaut 3.0 and could have been released with 2.5.x

Removed Liquibase from the list

**Comment by jameskleeh** [comment]
closing this as we have a milestone to release modules from now
