### ISSUE TITLE
Migrate graal-tests repositories to tests in the different modules' repositories

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-core#9083]
- [ ] [Micronaut Prometheus](https://github.com/micronaut-projects/micronaut-micrometer/issues/530)
- [x] [Micronaut Views](https://github.com/micronaut-projects/micronaut-views/issues/508)
- [x] Micronaut Views [3.9.x_freemarker](https://github.com/micronaut-graal-tests/micronaut-views-graal/tree/3.9.x_freemarker)
- [x] Micronaut Views [3.9.x_handlebars](https://github.com/micronaut-graal-tests/micronaut-views-graal/blob/3.9.x_handlebars)
- [x] Micronaut Views [3.9.x_pebble](https://github.com/micronaut-graal-tests/micronaut-views-graal/blob/3.9.x_pebble)
- [x] Micronaut Views [3.9.x_thymeleaf](https://github.com/micronaut-graal-tests/micronaut-views-graal/blob/3.9.x_thymeleaf)
- [x] Micronaut Views [3.9.x_velocity](https://github.com/micronaut-graal-tests/micronaut-views-graal/blob/3.9.x_velocity)
- [ ] [Micronaut AWS S3 & Parameter Store](https://github.com/micronaut-projects/micronaut-aws/issues/1675)
- [x] [Micronaut Servlet Jetty and Tomcat](https://github.com/micronaut-projects/micronaut-servlet/issues/423) - Done via the TCK which is more complete. 
- [x] [Micronaut Elasticsearch](https://github.com/micronaut-graal-tests/micronaut-elasticsearch-graal) done via https://github.com/micronaut-projects/micronaut-elasticsearch/pull/366
- [ ] [micronaut-aws-app-graal](https://github.com/micronaut-graal-tests/micronaut-aws-app-graal)
- [x] [micronaut-basic-app](https://github.com/micronaut-graal-tests/micronaut-basic-app)
- [x] [micronaut-cache-app](https://github.com/micronaut-graal-tests/micronaut-cache-graal)
- [x] [micronaut-cassandra-graal](https://github.com/micronaut-graal-tests/micronaut-cassandra-graal) - Fixed through [#307](https://github.com/micronaut-projects/micronaut-cassandra/pull/307)
- [x] [micronaut-email](https://github.com/micronaut-graal-tests/micronaut-email)
- [ ] [micronaut-function-aws-graal](https://github.com/micronaut-graal-tests/micronaut-function-aws-graal)
- [x] [micronaut-graphql-graal](https://github.com/micronaut-graal-tests/micronaut-graphql-graal)
- [x] [micronaut-grpc-graal](https://github.com/micronaut-graal-tests/micronaut-grpc-graal)
- [x] [micronaut-introspected-graal](https://github.com/micronaut-graal-tests/micronaut-introspected-graal)
- [x] [micronaut-kafka-graal](https://github.com/micronaut-graal-tests/micronaut-kafka-graal)
- [x] [micronaut-kotlin-graal](https://github.com/micronaut-graal-tests/micronaut-kotlin-graal)
- [ ] [micronaut-management-graal](https://github.com/micronaut-graal-tests/micronaut-management-graal)
- [x] [micronaut-rabbitmq-graal](https://github.com/micronaut-graal-tests/micronaut-rabbitmq-graal)
- [x] [micronaut-redis-graal](https://github.com/micronaut-graal-tests/micronaut-redis-graal) - [redis #364](https://github.com/micronaut-projects/micronaut-redis/pull/364)
- [ ] [micronaut-schedule-graal](https://github.com/micronaut-graal-tests/micronaut-schedule-graal)
- [ ] [micronaut-security-basic-auth-graal](https://github.com/micronaut-graal-tests/micronaut-security-basic-auth-graal)
- [ ] [micronaut-security-cookie-graal](https://github.com/micronaut-graal-tests/micronaut-security-cookie-graal)
- [ ] [micronaut-security-jwt-graal](https://github.com/micronaut-graal-tests/micronaut-security-jwt-graal)
- [ ] [micronaut-security-session-graal](https://github.com/micronaut-graal-tests/micronaut-security-session-graal)
- [ ] [micronaut-security-ldap-graal](https://github.com/micronaut-graal-tests/micronaut-security-ldap-graal)
- [ ] [micronaut-service-discovery-consul](https://github.com/micronaut-graal-tests/micronaut-service-discovery-consul)
- [ ] [micronaut-service-discovery-eureka](https://github.com/micronaut-graal-tests/micronaut-service-discovery-eureka)
- [ ] [micronaut-zipkin-graal](https://github.com/micronaut-graal-tests/micronaut-zipkin-graal)
- [ ] micronaut-data-jdbc-graal [3.9.x_h2](https://github.com/micronaut-graal-tests/micronaut-data-jdbc-graal/tree/3.9.x_h2)
- [ ] micronaut-data-jdbc-graal [3.9.x_mariadb](https://github.com/micronaut-graal-tests/micronaut-data-jdbc-graal/tree/3.9.x_mariadb)
- [ ] micronaut-data-jdbc-graal [3.9.x_mysql](https://github.com/micronaut-graal-tests/micronaut-data-jdbc-graal/tree/3.9.x_mysql)
- [ ] micronaut-data-jdbc-graal [3.9.x_oracle](https://github.com/micronaut-graal-tests/micronaut-data-jdbc-graal/tree/3.9.x_oracle)
- [ ] micronaut-data-jdbc-graal [3.9.x_postgres](https://github.com/micronaut-graal-tests/micronaut-data-jdbc-graal/tree/3.9.x_postgres)
- [ ] micronaut-data-jdbc-graal [3.9.x_sqlserver](https://github.com/micronaut-graal-tests/micronaut-data-jdbc-graal/tree/3.9.x_sqlserver)
- [ ] micronaut-data-jpa-graal [3.9.x_h2](https://github.com/micronaut-graal-tests/micronaut-data-jpa-graal/tree/3.9.x_h2)
- [ ] micronaut-data-jpa-graal [3.9.x_mariadb](https://github.com/micronaut-graal-tests/micronaut-data-jpa-graal/tree/3.9.x_mariadb)
- [ ] micronaut-data-jpa-graal [3.9.x_mysql](https://github.com/micronaut-graal-tests/micronaut-data-jpa-graal/tree/3.9.x_mysql)
- [ ] micronaut-data-jpa-graal [3.9.x_oracle](https://github.com/micronaut-graal-tests/micronaut-data-jpa-graal/tree/3.9.x_oracle)
- [ ] micronaut-data-jpa-graal [3.9.x_postgres](https://github.com/micronaut-graal-tests/micronaut-data-jpa-graal/tree/3.9.x_postgres)
- [ ] micronaut-data-jpa-graal [3.9.x_sqlserver](https://github.com/micronaut-graal-tests/micronaut-data-jpa-graal/tree/3.9.x_sqlserver)
- [x] micronaut-flyway-graal [3.9.x_h2](https://github.com/micronaut-graal-tests/micronaut-flyway-graal/tree/3.9.x_h2)
- [x] micronaut-flyway-graal [3.9.x_mariadb](https://github.com/micronaut-graal-tests/micronaut-flyway-graal/tree/3.9.x_mariadb)
- [x] micronaut-flyway-graal [3.9.x_postgres](https://github.com/micronaut-graal-tests/micronaut-flyway-graal/tree/3.9.x_postgres)
- [ ] micronaut-jooq-graal [3.9.x_h2](https://github.com/micronaut-graal-tests/micronaut-jooq-graal/tree/3.9.x_h2)
- [ ] micronaut-jooq-graal [3.9.x_postgres](https://github.com/micronaut-graal-tests/micronaut-jooq-graal/tree/3.9.x_postgres)
- [x] micronaut-liquibase-graal [3.9.x_h2](https://github.com/micronaut-graal-tests/micronaut-liquibase-graal/tree/3.9.x_h2)
- [x] micronaut-liquibase-graal [3.9.x_mariadb](https://github.com/micronaut-graal-tests/micronaut-liquibase-graal/tree/3.9.x_mariadb)
- [x] micronaut-liquibase-graal [3.9.x_postgres](https://github.com/micronaut-graal-tests/micronaut-liquibase-graal/tree/3.9.x_postgres)
- [ ]  micronaut-mqtt-graal [3.9.x_v3](https://github.com/micronaut-graal-tests/micronaut-mqtt-graal/tree/3.9.x_v3)
- [ ]  micronaut-mqtt-graal [3.9.x_v5](https://github.com/micronaut-graal-tests/micronaut-mqtt-graal/tree/3.9.x_v5)

**Comment by graemerocher** [comment]
I have ticked some boxes that already have test coverage

**Comment by sdelamo** [comment]
I checked Liquibase https://github.com/micronaut-projects/micronaut-liquibase/pull/353
