### ISSUE TITLE
Adding @MicronautTest annotation causes build to fail

### ISSUE THREAD

**Issue by markjfisher** [micronaut-projects/micronaut-core#979]
### Task List

- [X] Stacktrace (if present) provided
- [X] Example that reproduces the problem uploaded to Github
- [X] Full description of the issue provided (see below)

### Expected Behaviour

Adding `@MicronautTest` annotation should not cause compilation error

### Actual Behaviour

When running:

    ./gradlew build

Seeing error:

    * What went wrong:
    Execution failed for task ':compileTestGroovy'.
    > BUG! exception in phase 'semantic analysis' in source unit '<path>/src/test/groovy/mn/SpockSpec.groovy' sun.reflect.annotation.TypeNotPresentExceptionProxy

I've tried this with 1.0.1 and 1.0.0.RC2 releases (matched the version of the MicronautTest library).

### Environment Information

- **Operating System**: linux
- **Micronaut Version:** 1.0.1 and 1.0.0.RC2
- **JDK Version:** oracle 8

### Example Application
I've included two release versions in https://github.com/markjfisher/mn-spock

both are created with:

    mn create-app -l kotlin -f spock mn-spock-<release>
    cd <created dir>
    mn create-controller -l kotlin mn.Controller

and then adding:

    testCompile "io.micronaut.test:micronaut-test-spock:1.0.0.RC2"

to each version's build.gradle file and adding the annotation `@MicronautTest` to a spock test:

    package mn
    import io.micronaut.test.annotation.MicronautTest
    import spock.lang.Specification

    @MicronautTest
    class SpockSpec extends Specification {
        def 'it should compile'() {
            expect:
            true
        }
    }

**Comment by jameskleeh** [comment]
It's failing because you have junit5 on the classpath as well, but without the micronaut-test-junit5 library. Either add micronaut-test-junit5 or remove junit5 from the dependencies.
