### ISSUE TITLE
Support Java 21

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-core#9869]
[Java 21](https://openjdk.org/projects/jdk/21/) is scheduled to release by September 19, 2023. We need to update every module build to support it. We need to:

- [x] [Update project template Github Actions to test Java 21](https://github.com/micronaut-projects/micronaut-project-template/issues/402)
- [x] [Update Starter to generate projects with both either 17 and 21](https://github.com/micronaut-projects/micronaut-starter/issues/2051)
- [x] [Update Guides to test both 17 and 21](https://github.com/micronaut-projects/micronaut-guides/issues/1329)

**Comment by timyates** [comment]
This requires [Gradle 8.4 (currently)](https://docs.gradle.org/current/userguide/compatibility.html#java), which at time of writing isn't out

**Comment by subash89** [comment]
@sdelamo if we’re using maven, does that mean it’s fine to use jdk 21 ?
Any use of virtual threads in micronaut for jdk 21 ?

**Comment by yawkat** [comment]
AIUI there are issues with kotlin support on jdk 21, but otherwise maven should work fine.

You can use virtual threads in micronaut like this: https://docs.micronaut.io/latest/guide/index.html#virtualThreads

**Comment by sdelamo** [comment]
> @sdelamo if we’re using maven, does that mean it’s fine to use jdk 21 ?
> Any use of virtual threads in micronaut for jdk 21 ?

see @yawkat answer above. 

We are working on testing every module with both 17 and 21 and we will soon offer Java 21 in [Micronaut Launch](https://launch.micronaut.io) / CLI.

**Comment by OnnoH** [comment]
Was it also considered to implement an override of the base image via `-Dmicronaut.native-image.base-image=ghcr.io/graalvm/native-image-community:latest` for instance?

**Comment by sdelamo** [comment]
@timyates I think we can close this issue right?

**Comment by timyates** [comment]
👍
